name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-gate:
    name: Build Gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/cachix-action@v17
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build all derivations
        run: >-
          nix build --quiet
          .#checks.x86_64-linux.build
          .#checks.x86_64-linux.unit
          .#checks.x86_64-linux.lint

  unit:
    name: Unit tests
    needs: build-gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/cachix-action@v17
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix run --quiet .#unit

  lint:
    name: Lint
    needs: build-gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/cachix-action@v17
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix run --quiet .#lint
